"""Initial Migration

Revision ID: 1de3c7d0bf5e
Revises: 
Create Date: 2021-05-15 23:59:09.291329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de3c7d0bf5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('courses')
    op.drop_table('question_bank')
    op.drop_table('enrolments')
    op.drop_table('quizzes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('CourseID', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['CourseID'], ['Courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrolments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_bank',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), nullable=True),
    sa.Column('question_type', sa.INTEGER(), nullable=True),
    sa.Column('question_text', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=True),
    sa.Column('answer_text', sa.VARCHAR(length=128), nullable=True),
    sa.CheckConstraint('is_correct IN (0, 1)'),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
