def question_bank():
    json = {"response_code": 0, "results": [{"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "Which of the following sports is not part of the triathlon?",
                                             "correct_answer": "Horse-Riding",
                                             "incorrect_answers": ["Cycling", "Swimming", "Running"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "How many soccer players should be on the field at the same time?",
                                             "correct_answer": "22", "incorrect_answers": ["20", "24", "26"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "In what sport is a &quot;shuttlecock&quot; used?",
                                             "correct_answer": "Badminton",
                                             "incorrect_answers": ["Table Tennis", "Rugby", "Cricket"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "Which team won the 2015-16 English Premier League?",
                                             "correct_answer": "Leicester City",
                                             "incorrect_answers": ["Liverpool", "Cheslea", "Manchester United"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "In baseball, how many fouls are an out?",
                                             "correct_answer": "0", "incorrect_answers": ["5", "3", "2"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "The Rio 2016 Summer Olympics held it&#039;s closing ceremony on what date?",
                                             "correct_answer": "August 21",
                                             "incorrect_answers": ["August 23", "August 19", "August 17"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "Which country has hosted the 2018 FIFA World Cup?",
                                             "correct_answer": "Russia",
                                             "incorrect_answers": ["Germany", "United States", "Saudi Arabia"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "Who won the 2015 Formula 1 World Championship?",
                                             "correct_answer": "Lewis Hamilton",
                                             "incorrect_answers": ["Nico Rosberg", "Sebastian Vettel",
                                                                   "Jenson Button"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "Which team won 2014 FIFA World Cup in Brazil?",
                                             "correct_answer": "Germany",
                                             "incorrect_answers": ["Argentina", "Brazil", "Netherlands"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "In Baseball, how many times does the ball have to be pitched outside of the strike zone before the batter is walked?",
                                             "correct_answer": "4", "incorrect_answers": ["1", "2", "3"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "What team won the 2016 MLS Cup?",
                                             "correct_answer": "Seattle Sounders",
                                             "incorrect_answers": ["Colorado Rapids", "Toronto FC", "Montreal Impact"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "What year did the New Orleans Saints win the Super Bowl?",
                                             "correct_answer": "2010", "incorrect_answers": ["2008", "2009", "2011"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "This Canadian television sportscaster is known for his &quot;Hockey Night in Canada&quot; role, a commentary show during hockey games.",
                                             "correct_answer": "Don Cherry",
                                             "incorrect_answers": ["Don McKellar", "Don Taylor ", "Donald Sutherland"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "Which team has won the most Stanley Cups in the NHL?",
                                             "correct_answer": "Montreal Canadians",
                                             "incorrect_answers": ["Chicago Blackhawks", "Toronto Maple Leafs",
                                                                   "Detroit Red Wings"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "When was the first official international game played?",
                                             "correct_answer": "1872", "incorrect_answers": ["1880", "1863", "1865"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "Which boxer was banned for taking a bite out of Evander Holyfield&#039;s ear in 1997?",
                                             "correct_answer": "Mike Tyson",
                                             "incorrect_answers": ["Roy Jones Jr.", "Evander Holyfield",
                                                                   "Lennox Lewis"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "What is the most common type of pitch thrown by pitchers in baseball?",
                                             "correct_answer": "Fastball",
                                             "incorrect_answers": ["Slowball", "Screwball", "Palmball"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "What team did England beat to win in the 1966 World Cup final?",
                                             "correct_answer": "West Germany",
                                             "incorrect_answers": ["Soviet Union", "Portugal", "Brazil"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "In bowling, what is the term used for getting three consecutive strikes?",
                                             "correct_answer": "Turkey",
                                             "incorrect_answers": ["Flamingo", "Birdie", "Eagle"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "Who is often called &quot;the Maestro&quot; in the men&#039;s tennis circuit?",
                                             "correct_answer": "Roger Federer",
                                             "incorrect_answers": ["Bill Tilden", "Boris Becker", "Pete Sampras"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "What is the name of Manchester United&#039;s home stadium?",
                                             "correct_answer": "Old Trafford",
                                             "incorrect_answers": ["Anfield", "City of Manchester Stadium",
                                                                   "St James Park"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "The Los Angeles Dodgers were originally from what U.S. city?",
                                             "correct_answer": "Brooklyn",
                                             "incorrect_answers": ["Las Vegas", "Boston", "Seattle"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "&quot;Stadium of Light&quot; is the home stadium for which soccer team?",
                                             "correct_answer": "Sunderland FC",
                                             "incorrect_answers": ["Barcelona FC", "Paris Saints-Germain",
                                                                   "Manchester United"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "Which year did Jenson Button won his first ever Formula One World Drivers&#039; Championship?",
                                             "correct_answer": "2009", "incorrect_answers": ["2010", "2007", "2006"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "Which country will host the 2022 FIFA World Cup?",
                                             "correct_answer": "Qatar",
                                             "incorrect_answers": ["USA", "Japan", "Switzerland"]},
                                            {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                             "question": "Who won the UEFA Champions League in 2017?",
                                             "correct_answer": "Real Madrid C.F.",
                                             "incorrect_answers": ["Atletico Madrid", "AS Monaco FC",
                                                                   "Juventus F.C."]}]}
    return json
